### ISSUE TITLE
2017 data?

### ISSUE THREAD

**Issue by jungle-boogie** [lawlesst/baseballdb-datasette#1]
Hi There,

Thanks for creating and publishing the baseball data.

I'd like to know if you have the 2017 data available.

Thanks,
j.b.

**Comment by jungle-boogie** [comment]
Ah, I think I found 2017 data:

https://github.com/chadwickbureau/baseballdatabank

**Comment by lawlesst** [comment]
Glad you are finding it useful. The Chadwick data is slightly different than the Lahman data, not quite sure how much it varies but at the very least it's more current. I've added it to this instance of datasette so it can be queried. 

https://baseballdb.lawlesst.net/
